### ISSUE TITLE
Custom Font

### ISSUE THREAD

**Issue by yasiralijaved** [jjhesk/TagViewLayout#1]
Thanks for this great and easy-to-use library. I just want to use my custom font in tags.

**Comment by eversky** [comment]
Use setTagTypeface(Typeface typeface) to set TagView text typeface.

Typeface typeface = Typeface.createFromAsset(getAssets(), "iran_sans.ttf");
mTagContainerLayout.setTagTypeface(typeface);

**Comment by jjhesk** [comment]
yes i will add this in my way

**Comment by jjhesk** [comment]
this is done already.
