### ISSUE TITLE
How to change background and text color of a selected tag ?

### ISSUE THREAD

**Issue by sajib-4414** [jjhesk/TagViewLayout#3]
I am badly in need of this feature, User needs to get feedback by seeing the color of the selected tag .How can i Implement this ?

**Comment by jjhesk** [comment]
yes. it is now supported. check out the latest version.

**Comment by avinash8989** [comment]
How to make drawable for this. Is it different from Button drawable??

**Comment by larrytech7** [comment]
A drawable like this may be of help

```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_pressed="true">
        <color android:color="@color/red"/>
    </item>
</selector>
```
