### ISSUE TITLE
Not showing multiline tag

### ISSUE THREAD

**Issue by SanyasiraoM** [jjhesk/TagViewLayout#7]
I have a tag of length 100, but it's not showing it in multiple line at least not scrolling

Can I achieve that using your library

Thank you, @jjhesk Look at this. This is priority for me

And may I know the difference between your library and https://github.com/whilu/AndroidTagView

**Comment by jjhesk** [comment]
my mod has more supports on rending from using xml settings and it fixed a few bugs from the touch support

**Comment by jjhesk** [comment]
@SanyasiraoM you can go ahead and compare line by line from both repo. my has more supports and functions to try.
